---

 - name: Installation logiciel propriete
   become: yes
   apt:
     name: software-properties-common
     update_cache: yes
     state: present

 - name: Ajouter dans list repo le source php 
   become: yes
   template:
     src: add_repository_php.list.j2
     dest: /etc/apt/sources.list.d/ondrej-php-focal.list

 - name: Mise à jour liste des paquets
   become: yes
   apt:
     update_cache: yes

 - name: Installation php
   become: yes
   apt: 
     update_cache: yes
     name: "{{ item }}"
   loop: "{{ paquets }}"
   notify: Restart php service

 - name: Télécharger Composer 2.6.5
   become: yes
   get_url:
     url: https://getcomposer.org/download/2.6.5/composer.phar
     dest: /usr/local/bin/composer
     mode: +x

 - name: Configuration du site
   include: site.yml
...
